---
title: "Wordcloud"
author: "Alexander Noll"
date: "3 April 2016"
output: html_document
---

```{r setup}
# This package and the corresponding command makes sure, we all use the same
# versions of the packages
library(checkpoint)
checkpoint("2016-01-01")

library(dplyr)
library(purrr)
library(RColorBrewer)
library(readr)
library(stringr)
library(tidyr)
library(tm)
library(twitteR)
library(wordcloud)

source("../r/helper_functions/parse_diego_data.R")
```

This is a first check to see which words dominate. 

```{r 01_load_data}
train_data <- parse_diego_data("train")
```

## Wordcloud ADR

We plot a wordcloud of ADR events:

```{r 01_plot AE wordcloud, warning = FALSE}
pal <- brewer.pal(5, "Spectral")
tweets_AE <- 
    train_data %>% 
    filter(!is.na(annotated_text)) %$%
    tweet_text %>% 
    str_c(collapse = " ") %>% 
    str_replace("[^[:alnum:]]", "") %>% 
    stemDocument() %>%
    removeWords(stopwords("en")) 

wordcloud(tweets_AE, min.freq = 5, random.color = TRUE, colors = pal)
```

## Wordcloud Non ADR

```{r 01_plot NonAE wordcloud, warning = FALSE}
tweets_non_AE <- 
    train_data %>% 
    filter(is.na(annotated_text)) %$%
    tweet_text %>% 
    str_c(collapse = " ") %>% 
    str_replace("[^[:alnum:]]", "") %>% 
    stemDocument() %>%
    removeWords(stopwords("en")) 

wordcloud(tweets_non_AE, min.freq = 5, random.color = TRUE, colors = pal)
```

## Comparison cloud

```{r 01_compare, warning = FALSE}
corp <- Corpus(VectorSource(c(str_c(tweets_AE, collapse = ""), 
                              str_c(tweets_non_AE, collapse = " ")
                              )
                            )
               )

DocumentTermMatrix(corp) %>% 
    as.matrix %>%
    t %>% 
    comparison.cloud(max.words = 100)

```

